yk:
  profile: localhost
  version: 1-0-0
server:
  port: 8889
#jasypt:
#  encryptor:
#    password: OUTREA
spring:
  application:
    name: eureka-server-${yk.profile}-${yk.version}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  session:
    store-type: none
  http:
    converters:
      preferred-json-mapper: jackson # json 转换器, 接收数据和请求数据时使用
      preferred-xml-mapper: jackson # xml 转换器, 请求数据时使用
    encoding:
      force: true # 强制用 UTF-8 编码解析请求
    multipart:
      max-file-size: 10MB # 最大文件大小
      max-request-size: 10MB # 最大请求大小

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 123456

  cloud:
    loadbalancer:
      retry:
        enabled: true
mybatis:
  dialect: com.haiercash.hco.common.mybatis.dialect.OracleDialect
app:
  rest:
    APPCA: http://APPCA
#Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    # 是否从其他的服务中心同步服务列表
    fetch-registry: false
    # 是否把自己作为服务注册到其他服务注册中心
    register-with-eureka: false

ribbon:
  ConnectTimeout: 300000
  ReadTimeout: 600000
  MaxTotalHttpConnections: 5000
  MaxHttpConnectionsPerHost: 5000
  ActiveConnectionsLimit: 5000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 0
  eureka:
    enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
#security:
#  basic:
#    enabled: false

#静态资源读取路径
location:
  static: 'D:\\'


externalHttp:
  #通联
  tonglian:
    testTranURL: https://113.108.182.3/aipg/ProcessServlet
    merchantId: '200604000000445'
    pwd: '`12qwe'
    pfxPassword: '111111'
    pfxPath: 20060400000044502.p12
    tltcerPath: 'allinpay-pds.cer'
    userName: '20060400000044502'


